// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EM2AExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "EM2AExtension.a9cb4c0e-3880-4b66-b967-5eef7bdf2b66";
        public const string Name = "EM2AExtension";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
