// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EM2AExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string EM2AExtensionString = "dd666b1c-a255-45a1-9add-52d6be33d7b0";
        public static Guid EM2AExtension = new Guid(EM2AExtensionString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int AddProject = 0x0100;
        public const int AddMicroservice = 0x0200;
        public const int AddInterface = 0x0300;
        public const int AddFacade = 0x0400;
        public const int AddBL = 0x0500;
        public const int AddDL = 0x0600;
    }
}